[package]
name = "sinex"
version = "0.1.1"
license = "MIT OR Apache-2.0"
authors = ["Guillaume W. Bres <guillaume.bressaix@gmail.com>"]
description = "Package to parse and analyze SINEX data"
homepage = "https://github.com/gwbres/rinex/sinex"
repository = "https://github.com/gwbres/rinex/sinex"
keywords = ["sinex", "timing", "gps", "glonass", "galileo"]
categories = ["science", "parsing"]
edition = "2021"
readme = "README.md"

[features]

[build-dependencies]

[dependencies]
chrono = "0.4"
thiserror = "1"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.25"
rinex = { path = "../rinex", features = ["serde"] }
